"use strict";

grummer.store = {
  init() {
    grummer.breeds = this.breeds.sort((a, b) => a.title > b.title);
    grummer.categories = this.categories;
    grummer.servicesList = this.servicesList;
    grummer.ourWorks = this.ourWorks;
    grummer.questionsList = this.questions;
    grummer.feedbacksList = this.feedbacks;
  },
  breeds: [
    { title: "Помски", value: "pomski", type: "dog" },
    { title: "Эрдельтерьер", value: "erdenterier", type: "dog" },
    { title: "Йоркширский терьер, бивер-йорк", value: "york", type: "dog" },
    { title: "Шпиц", value: "shpits", type: "dog" },
    { title: "Шпиц малый", value: "shpits", type: "dog" },
    { title: "Шпиц японский", value: "shpits", type: "dog" },
    { title: "Шпиц карликовый (померанский)", value: "shpits", type: "dog" },
    { title: "Ши-Тцу", value: "shitsy", type: "dog" },
    { title: "Норвич-терьер", value: "norvich_terier", type: "dog" },
    { title: "Норфолк-терьер", value: "norfolk_terier", type: "dog" },
    { title: "Миттельшнауцер", value: "mittelshnatser", type: "dog" },
    { title: "Японский хин", value: "japan_hin", type: "dog" },
    {
      title: "Русская цветная болонка",
      value: "rus_color_balonka",
      type: "dog",
    },
    {
      title: "Мальтийская болонка (Мальтезе)",
      value: "malt_bolonka",
      type: "dog",
    },
    { title: "Бишон Фризе", value: "bishon_frieze", type: "dog" },
    { title: "Афганская борзая (АФГАН)", value: "afgan_borzaya", type: "dog" },
    { title: "Пекинес", value: "pekinez", type: "dog" },
    { title: "Русский охотничий спаниель", value: "rus_spaniel", type: "dog" },
    {
      title: "Американский Кокер-спаниель",
      value: "american_koker_spaniel",
      type: "dog",
    },
    { title: "Аффенпинчер", value: "affenpitcher", type: "dog" },
    { title: "Бассет-Хаунд", value: "basset_haund", type: "dog" },
    {
      title: "Английский Кокер-спаниель",
      value: "england_koker_spaniel",
      type: "dog",
    },
    { title: "Бобтейл", value: "bobtail", type: "dog" },
    { title: "Акита-Ину", value: "akita_inu", type: "dog" },
    { title: "Бульдог Английский", value: "buldog_england", type: "dog" },
    { title: "Бульдог Французский", value: "buldog_franch", type: "dog" },
    { title: "Бедлингтон-терьер", value: "bedlington_terier", type: "dog" },
    { title: "Вельш-Корги Пемброк", value: "velsh_korgi", type: "dog" },
    { title: "Китайская хохлатая", value: "сhinese_hohlataya", type: "dog" },
    { title: "Вельштерьер", value: "velshterier", type: "dog" },
    { title: "Бультерьер", value: "bulterier", type: "dog" },
    { title: "Пудель КОРОЛЕВСКИЙ", value: "pudel_king", type: "dog" },
    { title: "Пудель большой", value: "pudel_big", type: "dog" },
    { title: "Русский той-терьер", value: "rus_toi", type: "dog" },
    {
      title: "Пудель (той и карликовый)",
      value: "pudel_toy_and_karlick",
      type: "dog",
    },
    {
      title: "Пудель (Малый. До 55см в холке)",
      value: "pudel_litle",
      type: "dog",
    },
    { title: "Метис/Дворняга", value: "metis_dvor", type: "dog" },
    { title: "Бриар", value: "briar", type: "dog" },
    { title: "Папильон", value: "papilion", type: "dog" },
    {
      title: "Фокстерьер жескошерстный",
      value: "foxterier_hardhair",
      type: "dog",
    },
    {
      title: "Гриффон (брюсельский, бельгийский)",
      value: "griffon",
      type: "dog",
    },
    {
      title: "Золотистый ретривер (голден)",
      value: "gold_retriver",
      type: "dog",
    },
    {
      title: "Алабай (средне-азиатская овчарка)",
      value: "alabai",
      type: "dog",
    },
    { title: "Бордер колли", value: "kolli", type: "dog" },
    { title: "Вест-хайленд-вайт-терьер", value: "vest_hailend", type: "dog" },
    { title: "Чау-Чау", value: "chau_chau", type: "dog" },
    { title: "Ньюфаундленд", value: "newfaunlend", type: "dog" },
    { title: "Сеттер (ирл, гордон, англ)", value: "setter", type: "dog" },
    { title: "Мопс", value: "mops", type: "dog" },
    { title: "Сиба-ину", value: "siba_inu", type: "dog" },
    { title: "Скотч-терьер", value: "scotch_terier", type: "dog" },
    { title: "Силихем-терьер", value: "silihem_terier", type: "dog" },
    { title: "Грифон", value: "grifon", type: "dog" },
    { title: "Такса гладкошерстная", value: "taksa", type: "dog" },
    { title: "Такса жесткошерстная", value: "taksa_hard", type: "dog" },
    { title: "Такса длинношерстная", value: "taksa_longhair", type: "dog" },
    { title: "Цвергшнауцер", value: "shwergshnautser", type: "dog" },
    { title: "Ризеншнауцер", value: "risenshnautser", type: "dog" },
    { title: "Самоед", value: "samoed", type: "dog" },
    { title: "Хаски", value: "haski", type: "dog" },
    { title: "Ротвейлер", value: "rotveiler", type: "dog" },
    { title: "Чихуахуа", value: "chihuahua", type: "dog" },
    { title: "Шарпей", value: "sharpei", type: "dog" },
    { title: "Шелти", value: "shelti", type: "dog" },
    { title: "Бигль", value: "bigle", type: "dog" },
    {
      title: "Московская сторожевая",
      value: "moskow_storogevaya",
      type: "dog",
    },
    { title: "Спрингер-спаниель", value: "springer_spaniel", type: "dog" },
    { title: "Джек-рассел-терьер", value: "jack_rassel", type: "dog" },
    { title: "Лабрадор", value: "labrador", type: "dog" },
    { title: "Лабрадудель", value: "labradudel", type: "dog" },
    { title: "Мальтипу", value: "maltipu", type: "dog" },
    { title: "Аляскинский маламут", value: "malamut", type: "dog" },
    { title: "Черный русский терьер", value: "black_rus_terier", type: "dog" },
    { title: "Ирландский терьер", value: "ireland_terier", type: "dog" },
    {
      title: "Ирландский мягкошерстный пшеничный терьер",
      value: "ireland_terier_soft",
      type: "dog",
    },
    { title: "Немецкая овчарка", value: "deutsch_ovcharka", type: "dog" },
    {
      title: "Пиренейская овчарка",
      value: "pireneiskaya_ovcharka",
      type: "dog",
    },
    { title: "Сенбернар", value: "senbernar", type: "dog" },
    { title: "Далматин", value: "dalmatin", type: "dog" },
    {
      title: "Кавалер Кинг Чарльз спаниель",
      value: "kavaler_king_spaniel",
      type: "dog",
    },
    { title: "Бернский Зенненхунд", value: "bern_zennenhund", type: "dog" },
    { title: "Боксер", value: "boxer", type: "dog" },
  ],
  categories: [
    { title: "Все", value: "", icon: "" },
    { title: "Гигиена", value: "hygiene", icon: "wash" },
    { title: "Шерсть", value: "wool", icon: "barbershop" },
    { title: "Когти", value: "claw", icon: "foot" },
    { title: "Зубы", value: "tooth", icon: "tooth" },
    { title: "Доп. услуги", value: "additional", icon: "plus-box" },
  ],
  servicesList: {
    dogs: [
      {
        id: 0,
        title: "SPA-комплекс",
        animal: "dog",
        price: "1350 - 2400",
        time: "1.5 часа",
        category: "hygiene",
        text: "по восстановлению шерсти с маслом арганы",
        img: "spa.svg",
      },
      {
        id: 1,
        title: "Озонотерапия",
        animal: "dog",
        price: "1700 - 2100",
        time: "2.5 часа",
        category: "hygiene",
        text: "с маской",
        img: "ozon-mask.svg",
      },
      {
        id: 2,
        title: "Озонотерапия",
        animal: "dog",
        price: "1000",
        time: "1 час",
        category: "hygiene",
        text: "без маски",
        img: "ozon-nomask.svg",
      },

      {
        id: 3,
        title: "Вычесывание",
        animal: "dog",
        price: "1000",
        time: "1 час",
        category: "wool",
        text: "",
        img: "comb-out.svg",
      },
      {
        id: 4,
        title: "Расчёсывание колтунов",
        animal: "dog",
        price: "1000",
        time: "1 час",
        category: "hygwooliene",
        text: "Дополнительная услуга без релаксанта (2мм) (в присутствии хозяина)",
        img: "comb-kolts.svg",
      },
      {
        id: 5,
        title: "Стрижка под машику",
        price: "0",
        animal: "dog",
        time: "0",
        img: "spa.svg",
        text: "",
        category: "wool",
      },
      {
        id: 6,
        title: "Подстригание когтей",
        price: "0",
        animal: "dog",
        time: "0",
        img: "spa.svg",
        text: "",
        category: "claw",
      },
      {
        id: 7,
        title: "Чистка параанальных желез",
        price: "300",
        animal: "additional",
        time: "0",
        img: "spa.svg",
        text: "",
        category: "hygiene",
      },
      {
        id: 8,
        title: "Модельная стрижка",
        price: "300",
        animal: "dog",
        time: "0",
        img: "spa.svg",
        text: "",
        category: "wool",
      },
      {
        id: 9,
        title: "Полный тримминг",
        animal: "dog",
        price: "2000",
        time: "1 час",
        category: "wool",
        text: "ручная щипка",
        img: "trim.svg",
      },
      {
        id: 10,
        title: "Сбривание колтунов",
        animal: "dog",
        price: "500",
        time: "30 мин",
        category: "wool",
        text: "без релаксанта (2мм) (в присутствии хозяина)",
        img: "trim-kolt.svg",
      },

      {
        id: 11,
        title: "Подпил когтей",
        animal: "dog",
        price: "400 - 600",
        time: "1 час",
        category: "claw",
        text: "",
        img: "foot.svg",
      },

      {
        id: 12,
        title: "Ультразвуковая чистка зубов",
        animal: "dog",
        price: "2500 - 4500",
        time: "1.5 часа",
        category: "tooth",
        text: "",
        img: "tooth.svg",
      },
      {
        id: 13,
        title: "Снятие зубного камня и налета",
        animal: "dog",
        price: "1000 - 1500",
        time: "30 мин",
        category: "tooth",
        text: "механически",
        img: "tooth.svg",
      },
      {
        id: 14,
        title: "Чистка зубов пастой",
        animal: "dog",
        price: "350 - 550",
        time: "30 мин",
        category: "tooth",
        text: "",
        img: "toothpaste.svg",
      },
      {
        id: 15,
        title: "Полировка зубов пастой",
        animal: "dog",
        price: "1000",
        time: "1 час",
        category: "tooth",
        text: "",
        img: "toothpaste.svg",
      },

      {
        id: 16,
        title: "Антипаразитальный комплекс",
        animal: "dog",
        price: "400",
        time: "30 мин",
        category: "additional",
        text: "",
        img: "antiparasite.svg",
      },
      {
        id: 17,
        title: "Обработка РЕК",
        animal: "dog",
        price: "200",
        time: "30 мин",
        category: "additional",
        text: "",
        img: "rek.svg",
      },
      {
        id: 18,
        title: "Снятий клеща + обработка раны",
        animal: "dog",
        price: "100",
        time: "15 мин",
        category: "additional",
        text: "",
        img: "tick.svg",
      },
      {
        id: 19,
        title: "Агрессивность животного",
        animal: "dog",
        price: "500 - 1000",
        time: "",
        category: "additional",
        text: "на усмотрение мастера",
        img: "bad-animal.svg",
      },
    ],
    cats: [
      {
        id: 20,
        title: "Стрижка",
        animal: "cat",
        price: "от 850",
        time: "1 час",
        category: "wool",
        text: "",
        img: "barbershop.svg",
      },
      {
        id: 21,
        title: "Экспресс линька",
        animal: "cat",
        price: "1300",
        time: "1 час",
        category: "wool",
        text: "",
        img: "express-linka.svg",
      },
      {
        id: 22,
        title: "Окрашивание шерсти",
        animal: "cat",
        price: "от 1500",
        time: "",
        category: "wool",
        text: "Дополнительная услуга",
        img: "color-wool.svg",
      },
      {
        id: 23,
        title: "Расчёсывание колтунов",
        animal: "cat",
        price: "600",
        time: "",
        category: "wool",
        text: "В присутствии хозяина",
        img: "comb-kolts.svg",
      },
      {
        id: 24,
        title: "Сбривание колтунов",
        animal: "cat",
        price: "200 - 500",
        time: "",
        category: "wool",
        text: "В присутствии хозяина",
        img: "trim-kolt.svg",
      },
      {
        id: 25,
        title: "Гигиена-комплекс",
        animal: "cat",
        price: "1500",
        time: "",
        category: "hygiene",
        text: "Стрижка когтей,чистка ушей,ультразвуковая чистка зубов,чистка анальных желёз",
        img: "wash-plus.svg",
      },
      {
        id: 26,
        title: "Мытьё",
        animal: "cat",
        price: "250",
        time: "30 мин",
        category: "hygiene",
        text: "",
        img: "wash.svg",
      },
      {
        id: 27,
        title: "Стрижка под машику",
        price: "0",
        animal: "cat",
        time: "0",
        img: "spa.svg",
        text: "",
        category: "wool",
      },
      {
        id: 28,
        title: "Подстригание когтей",
        price: "от 200",
        animal: "cat",
        time: "0",
        img: "spa.svg",
        text: "",
        category: "claw",
      },
      {
        id: 29,
        title: "Подпил когтей",
        animal: "cat",
        price: "400 - 600",
        time: "1 час",
        category: "claw",
        text: "",
        img: "foot.svg",
      },
      {
        id: 30,
        title: "Модельная стрижка",
        price: "300",
        animal: "cat",
        time: "0",
        img: "spa.svg",
        text: "",
        category: "wool",
      },

      {
        id: 31,
        title: "Ультразвуковая чистка зубов",
        animal: "cat",
        price: "2500 - 4500",
        time: "1.5 часа",
        category: "tooth",
        text: "",
        img: "tooth.svg",
      },
      {
        id: 32,
        title: "Снятие зубного камня и налета",
        animal: "cat",
        price: "1000 - 1500",
        time: "30 мин",
        category: "tooth",
        text: "механически",
        img: "tooth.svg",
      },
      {
        id: 33,
        title: "Чистка зубов пастой",
        animal: "cat",
        price: "350 - 550",
        time: "30 мин",
        category: "tooth",
        text: "",
        img: "toothpaste.svg",
      },
      {
        id: 34,
        title: "Полировка зубов пастой",
        animal: "cat",
        price: "1000",
        time: "1 час",
        category: "tooth",
        text: "",
        img: "toothpaste.svg",
      },
    ],
    additional: [
      {
        id: 35,
        title: "Чистка параанальных желез",
        price: "300",
        animal: "",
        time: "1",
        img: "spa.svg",
        text: "",
        category: "additional",
      },

      {
        id: 36,
        title: "Выведение блох и удаление клещей",
        animal: "",
        price: "300",
        time: "",
        category: "additional",
        text: "Дополнительная услуга",
        img: "tick.svg",
      },
      {
        id: 37,
        title: "Помощь второго грумера",
        animal: "",
        price: "600",
        time: "",
        category: "additional",
        text: "Дополнительная услуга",
        img: "help-grummer.svg",
      },
      {
        id: 38,
        title: "Сушка",
        price: "0",
        animal: "",
        time: "0",
        img: "spa.svg",
        text: "",
        category: "additional",
      },
      // {
      //   title: "Зоотакси",
      //   animal: "",
      //   price: "от 300",
      //   time: "",
      //   category: "additional",
      //   text: "заберем и привезем обратно после процедуры",
      //   img: "zootaxi.svg",
      // },
    ],
  },
  ourWorks: [
    "slide_1.jpg",
    "slide_2.jpg",
    "slide_3.jpg",
    "slide_4.jpg",
    "slide_5.jpg",
    "slide_6.jpg",
    "slide_7.jpg",
  ],
  feedbacks: [
    {
      img: "noavatar.png",
      text: "Не в первый раз посещаем данный салон. Сотрудники всегда вежливые. Приходила когда у лайки начиналась сезонная линька. У тех кто лайки или хаски, маламуты, самоеды и т.д. поймут что шерсть в такие дни",
    },
    {
      img: "noavatar.png",
      text: "Раньше ходила в другие салоны, но только в этом салоне девочки поняли, что я хочу.",
    },
    {
      img: "noavatar.png",
      text: "Не в первый раз посещаем данный салон.",
    },
    {
      img: "noavatar.png",
      text: "Не в первый раз посещаем данный салон. Сотрудники всегда вежливые. Приходила когда у лайки начиналась сезонная линька. У тех кто лайки или хаски, маламуты, самоеды и т.д. поймут что шерсть в такие дни",
    },
    {
      img: "noavatar.png",
      text: "Не в первый раз посещаем данный салон. Сотрудники всегда вежливые. Приходила когда у лайки начиналась сезонная линька. У тех кто лайки или хаски, маламуты, самоеды и т.д. поймут что шерсть в такие дни",
    },
    {
      img: "noavatar.png",
      text: "Не в первый раз посещаем данный салон. Сотрудники всегда вежливые. Приходила когда у лайки начиналась сезонная линька. У тех кто лайки или хаски, маламуты, самоеды и т.д. поймут что шерсть в такие дни",
    },
    {
      img: "noavatar.png",
      text: "Не в первый раз посещаем данный салон. Сотрудники всегда вежливые. Приходила когда у лайки начиналась сезонная линька. У тех кто лайки или хаски, маламуты, самоеды и т.д. поймут что шерсть в такие дни",
    },
    {
      img: "noavatar.png",
      text: "Норм салон",
    },
  ],
};
